import Button from "@/components/button";
import { Nav } from "@/components/Nav";
import { About } from "@/home/About";
import { Contact } from "@/home/Contact";
import { Footer } from "@/home/Footer";
import { Hero } from "@/home/Hero";
import { Projects } from "@/home/Projects";
import Stack from "@/home/Stack";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tyler Duncan Sotubo | Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark:bg-skin-background">
        <Nav />
        <Hero />
        <About />
        <Stack />
        <div className="my-4 flex justify-center">
          <Link href="/resume">
            <Button name="My Experience" color="bg-skin-herobackground" />
          </Link>
        </div>
        <Projects />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
